# app.yaml
command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
env:
  - name: "PYTHONUNBUFFERED"
    value: "1"
# Optional: set any environment variables needed for Google API keys, e.g.:
  - name: "GOOGLE_APPLICATION_CREDENTIALS"
    value: "/secrets/google_creds.json"
